language: python
python:
  - 2.7
matrix:
  include:
    # Also build with Twisted 13.2.0 for Ubuntu.
    - python: 2.7
      env: TWISTED_VERSION=13.2.0

install:
  - pip install -U pip
  - if [ ! -z "$TWISTED_VERSION" ]; then pip install "Twisted==$TWISTED_VERSION"; fi
  - pip install .
  - pip install flake8
services:
  - redis-server
script:
  - trial docker_xylem
  - flake8
